# Generated by Django 5.2.18 on 2026-10-07 01:32

import convenios.documentos
import convenios.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', convenios.models.DocumentoField(help_text='Com ou sem pontuação. Pessoa física (ex.: profissional liberal) usa CPF.', max_length=14, unique=True, validators=[convenios.documentos.validar_documento], verbose_name='CPF/CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='razão social / nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('ensino_privada', 'Instituição de Ensino Privada'), ('empresa_privada', 'Empresa Privada'), ('ong_oscip', 'ONGs e OSCIPs'), ('orgao_publico', 'Órgãos dos Governos Federal, Estadual e Municipal'), ('profissional_liberal', 'Profissional Liberal'), ('agente_integracao', 'Agente de Integração'), ('ensino_publica', 'Instituições de Ensino Públicas'), ('microempresa', 'Microempresas'), ('outros', 'Outros')], max_length=30)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=100)),
                ('ramo_atividade', models.CharField(blank=True, max_length=255, verbose_name='ramo de atividade')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Ex.: PR-212/2026', max_length=30, verbose_name='nº do convênio')),
                ('processo_sei', models.CharField(blank=True, help_text='Ex.: 23069.179497/2026-46', max_length=25, verbose_name='nº do processo SEI')),
                ('resolucao_cep', models.CharField(blank=True, max_length=100, verbose_name='Resolução CEP')),
                ('resolucao_cep_url', models.URLField(blank=True, verbose_name='link da Resolução CEP')),
                ('objeto', models.TextField(blank=True)),
                ('minuta', models.CharField(choices=[('padrao_uff', 'Padrão UFF'), ('externa', 'Externa (proposta pela concedente)')], default='padrao_uff', max_length=20)),
                ('origem', models.CharField(choices=[('concedente', 'Concedente procurou a UFF'), ('uff', 'UFF procurou a concedente')], default='concedente', max_length=20)),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('fim_vigencia', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('situacao', models.CharField(choices=[('em_tramitacao', 'Em tramitação'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='em_tramitacao', max_length=20, verbose_name='situação')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='observações internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='convenios.concedente')),
            ],
            options={
                'verbose_name': 'convênio',
                'ordering': ['-inicio_vigencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EtapaConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('documentacao_recebida', 'Documentação recebida'), ('analise', 'Análise da documentação'), ('termo_preparado', 'Termo de convênio preparado'), ('assinatura_concedente', 'Assinado pela concedente'), ('assinatura_pro_reitor', 'Assinado pelo pró-reitor'), ('ratificacao', 'Ratificação'), ('extrato_bs', 'Extrato publicado no Boletim de Serviço'), ('outra', 'Outra (descrever na observação)')], max_length=30)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'etapa',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('numero',), name='convenio_numero_unico', violation_error_message='Já existe convênio com este número.'),
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.CheckConstraint(condition=models.Q(('fim_vigencia__gt', models.F('inicio_vigencia')), ('inicio_vigencia__isnull', True), ('fim_vigencia__isnull', True), _connector='OR'), name='convenio_fim_depois_do_inicio', violation_error_message='O fim da vigência deve ser depois do início.'),
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('situacao', 'finalizado'), _negated=True), models.Q(('fim_vigencia__isnull', False), ('inicio_vigencia__isnull', False), models.Q(('numero', ''), _negated=True)), _connector='OR'), name='convenio_finalizado_completo', violation_error_message='Finalizado exige número e datas de vigência.'),
        ),
    ]
