# Generated by Django 5.2.18 on 2026-10-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_grupo_divisao_estagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fim_vigencia', models.DateField()),
                ('antecedencia_dias', models.PositiveIntegerField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'alerta de vencimento',
                'verbose_name_plural': 'alertas de vencimento',
                'constraints': [models.UniqueConstraint(fields=('convenio', 'fim_vigencia', 'antecedencia_dias'), name='alerta_unico')],
            },
        ),
    ]
