# Generated by Django 5.2.18 on 2026-10-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_permissao_alertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='finalizado_em',
            field=models.DateField(blank=True, editable=False, help_text='Preenchido ao marcar como finalizado; base do tempo de tramitação (MS05).', null=True, verbose_name='finalizado em'),
        ),
    ]
