# Generated by Django 5.2.18 on 2026-10-07 11:39

import convenios.documentos
import convenios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0005_finalizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='id_drupal',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Origem na importação do estagio.uff.br (RF07); permite reimportar sem duplicar.', null=True, unique=True, verbose_name='nó no Drupal'),
        ),
        migrations.AlterField(
            model_name='concedente',
            name='documento',
            field=convenios.models.DocumentoField(blank=True, help_text='Com ou sem pontuação. Pessoa física (ex.: profissional liberal) usa CPF.', max_length=14, null=True, unique=True, validators=[convenios.documentos.validar_documento], verbose_name='CPF/CNPJ'),
        ),
    ]
